version: '3.2'
services:
  redis-db:
    image: redis:latest
    hostname: redis-db
    ports:
      -  "6379:6379/tcp"
    dns:
      - 10.0.0.71
      - 10.0.0.72
    volumes:
      - /storage/network-services/redis/:/data
    networks:
      - bbb_daemon_network

  bbb-server:
    hostname: bbb-server
    image: lnlscon/bbb-daemon-container:latest
    ports:
      -  "1026:1026"
      -  "4850:4850"
      -  "6789:6789/tcp"
      -  "9877:9877/tcp"
      -  "9876:9876/udp"
    dns:
      - 10.0.0.71
      - 10.0.0.72
    env_file:
      -  /home/srv1/repository/bbb-daemon/docker/bbb-server/bbb-server.env
    networks:
      - bbb_daemon_network
    depends_on:
      - redis
    deploy:
      replicas: 1

networks:
  bbb_daemon_network:
    ipam:
      config:
        - subnet: 192.168.10.0/24
