version: '3.3'
services:
  redis:
    image: redis:latest 
    container_name: redis_bbb
    ports:
      -  "6379:6379"
    volumes:
      - bbb-redis-data:/data

  bbb-server-service:
    container_name: bbb-serv-cont
    image: lnlscon/bbb-daemon-container:bbb-server
    ports:
      -  "6789:6789"
      -  "9876:9876"
    dns:
      - 10.0.0.71
      - 10.0.0.72
    env_file:
      -  /root/bbb-daemon/docker/bbb-server/bbb-server.env
    depends_on:
      -  redis

volumes:
  bbb-redis-data:
